__default__:
  time: "24:00:00"
  nodes: 1
  cpus-per-task: 4
  account: csu101_alpine1
  partition: amilan128c,amilan
  qos: normal

run_lostruct_global:
  time: "12:00:00"
  mem: "256G"
  account: csu101_alpine1
  partition: amem
  qos: mem
